include: package:dart_flutter_team_lints/analysis_options.yaml
linter:
  rules:
    - avoid_print
    - public_member_api_docs
analyzer:
  exclude:
    - tool/*
  errors:
    lines_longer_than_80_chars: ignore
    avoid_print: error
    inference_failure_on_untyped_parameter: ignore
    avoid_dynamic_calls: ignore
    invalid_assignment: ignore
    argument_type_not_assignable: ignore
    return_of_invalid_type: ignore
    omit_local_variable_types: false

