name: proxy_recrypt
description: A proxy re-encryption library for Dart.
version: 1.1.1
repository: https://github.com/affinidi/recrypt-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: ^3.1.1       # For hex encoding/decoding
  crypto: ^3.0.3        # For SHA256 and other crypto functions
  cryptography: ^2.7.0
  encrypt: ^5.0.3       # For AES encryption
  pointycastle: ^4.0.0  # For elliptic curve operations


dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  lints: ^6.0.0
  melos: ^6.3.3  
  test: ^1.24.0


dependency_overrides:
  pointycastle: ^4.0.0 # override as all other lib versions use version 4

topics:
  - proxy-reencryption

command:
  version:
    changelogCommitBodies:
      include: true
      onlyBreaking: false
