name: proxy_recrypt
description: Proxy Re-Encryption (PRE) utilities for Dart enabling secure, server-mediated sharing of encrypted data without exposing plaintext.
version: 1.1.2
repository: https://github.com/affinidi/recrypt-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert: ^3.1.2       # For hex encoding/decoding
  crypto: ^3.0.6        # For SHA256 and other crypto functions
  cryptography: ^2.7.0
  encrypt: ^5.0.3       # For AES encryption
  pointycastle: ^3.7.3  # For elliptic curve operations


dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  melos: ^6.3.3  
  test: ^1.26.3


topics:
  - proxy-reencryption

command:
  version:
    changelogCommitBodies:
      include: true
      onlyBreaking: false

# This package supports only Linux and macOS.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
