name: release

on:
  push:
    branches:
      - test/dart-security-scanner
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello World"

  dart-security-scan:
    uses: affinidi/pipeline-security/.github/workflows/rust-scanner.yml@main
    secrets: inherit
